variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
- name: $(date:yyyyMMdd)$(rev:.r)
- name: BuildConfiguration
  value: 'Release'
- name: buildOutputFolder
  value: $(Build.ArtifactStagingDirectory)
trigger:
  branches:
    include:
    - refs/heads/master
resources:
  repositories:
  - repository: self
    type: git
    ref: master
pool:
  name: SPool
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: SPool
  
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      ConnectedServiceName: caf1b5a2-9dfd-4324-abee-ba75eb051e84
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
      feedRestore: ea7af1b7-ce46-4865-aa8f-bf0fe61f53df
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      ConnectedServiceName: caf1b5a2-9dfd-4324-abee-ba75eb051e84
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    enabled: False
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      ConnectedServiceName: caf1b5a2-9dfd-4324-abee-ba75eb051e84
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      #TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
      ArtifactName: 'drop'
      publishLocation: 'Container'   
        
- job: Deploy
  displayName: 'Deploy to IIS Web Server'
  dependsOn: Job_1
  condition: succeeded()
  pool:
    name: 'SPool'  # Ensure this is the correct pool with your self-hosted agent
  steps:
    # Step 1: Download build artifacts
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: 'specific'
        project: $(System.TeamProject)
        definition: '13'  # $(Build.DefinitionId)
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(build.artifactstagingdirectory)' #'$(Build.SourcesDirectory)'
    - task: CmdLine@2
      inputs:
          script: |
            echo Hello world-2
            echo  $(Build.SourcesDirectory)
            echo Hello world-2
    # Step 2: Copy Web API files to IIS server folder
    - task: ExtractFiles@1
      displayName: 'Extract published files'
      inputs:
        archiveFilePatterns: '$(build.artifactstagingdirectory)/drop/*.zip'  # Path to the zip file in the 'drop' folder
        destinationFolder: '$(build.artifactstagingdirectory)/extracted'  # Destination folder where files will be extracted
    - task: CopyFiles@2
      displayName: 'Copy Web API files to IIS folder'
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)/extracted' #'$(buildOutputFolder)/webapi'
        Contents: '**'
        TargetFolder: 'C:\inetpub\wwwroot\newfolder'  # Change this path to your IIS folder   
    - task: CmdLine@2
      inputs:
          script: |
            echo Artifact staging directory-Hello world-3
            echo  $(Build.ArtifactStagingDirectory)
            echo Hello world-3

            echo Sources Directory- Hello world-3
            echo  $(Build.SourcesDirectory)
            echo Hello world-3
...
